### ISSUE TITLE
Pose V2 requires lixit information

### ISSUE THREAD

**Issue by hessil** [KumarLabJax/JABS-behavior-classifier#1]
Attempting to train classifier on pose v2 files which have no lixit raises the error:
`KeyError: "Unable to open object (object 'distance_to_lixit' doesn't exist)"`

**Comment by gbeane** [comment]
is there a full stack trace, or just this error message?

**Comment by hessil** [comment]
`Traceback (most recent call last):
  File "/Users/hessil/Downloads/JABS-behavior-classifier-main 2/src/ui/training_thread.py", line 58, in run
    id_processed
  File "/Users/hessil/Downloads/JABS-behavior-classifier-main 2/src/project/project.py", line 660, in get_labeled_features
    extended_features=self._enabled_extended_features
  File "/Users/hessil/Downloads/JABS-behavior-classifier-main 2/src/feature_extraction/features.py", line 113, in __init__
    self.__load_from_file()
  File "/Users/hessil/Downloads/JABS-behavior-classifier-main 2/src/feature_extraction/features.py", line 177, in __load_from_file
    self._per_frame[feature] = feature_grp[feature][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/hessil/Downloads/JABS-behavior-classifier-main 2/jabs.venv/lib/python3.7/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'distance_to_lixit' doesn't exist)"`

**Comment by gbeane** [comment]
It turns out I had already fixed this a few weeks before I left JAX, but hadn't committed the changes to git.
