### ISSUE TITLE
Random Forest Classifier in Dev Branch

### ISSUE THREAD

**Issue by luciazhxng** [KumarLabJax/JABS-behavior-classifier#39]
Traceback (most recent call last):
  File "/behavior-classifier/src/ui/training_thread.py", line 85, in run
    self._classifier.train(data)
  File "/behavior-classifier/src/classifier/classifier.py", line 411, in train
    self._classifier = self._fit_random_forest(features, labels,
  File "/behavior-classifier/src/classifier/classifier.py", line 544, in _fit_random_forest
    return classifier.fit(features.fillna(0), labels)
  File "/usr/local/lib/python3.10/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
    X, y = self._validate_data(
  File "/usr/local/lib/python3.10/site-packages/sklearn/base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1147, in check_X_y
    X = check_array(
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 959, in check_array
    _assert_all_finite(
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 124, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 173, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains infinity or a value too large for dtype('float32').

JABS-GUI-2024-06-25-588eeec.sif

/projects/kumar-lab/zhanglu/stretch-attend

**Comment by SkepticRaven** [comment]
Just adding some additional notes:
This is related to branch https://github.com/KumarLabJax/JABS-behavior-classifier/tree/update-prediction-format at commit head https://github.com/KumarLabJax/JABS-behavior-classifier/commit/588eeecf6957d327272918b9c6a9536fdd8bff2c

**Comment by SkepticRaven** [comment]
Potential patch: https://github.com/KumarLabJax/JABS-behavior-classifier/commit/8ab8c5e18b33bedcd51afbdd8a65edbc9368d3ad
infinite values were making their way through from the newly introduced kurtosis and potentially skew functions. Will close if confirmed fixed.
